# Generated by Django 5.2.5 on 2025-09-16 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(default='avatars/default.jpg', upload_to='avatars/')),
                ('isPublic', models.BooleanField(default=True)),
                ('showStats', models.BooleanField(default=True)),
                ('animeCount', models.PositiveIntegerField(default=0)),
                ('episodesWatched', models.PositiveIntegerField(default=0)),
                ('joinedDate', models.DateTimeField(auto_now_add=True)),
                ('lastOnline', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
