# Generated by Django 5.2.5 on 2025-09-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('CUSTOM', 'Customizado'), ('NONE', 'Prefiro não dizer')], default='NONE', max_length=20),
        ),
    ]
