# Generated by Django 5.2.5 on 2025-09-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_options_friendship'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user2',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
