# Generated by Django 5.2.5 on 2025-10-21 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_friendship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='isPublic',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='showStats',
        ),
    ]
