# Generated by Django 5.2.5 on 2025-10-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_friendship_remove_userprofile_ispublic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='showStats',
            field=models.BooleanField(default=True),
        ),
    ]
