# Generated by Django 5.2.5 on 2025-10-20 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anime',
        ),
    ]
