# Generated by Django 5.2.5 on 2025-09-24 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_id', models.IntegerField()),
                ('score', models.IntegerField(choices=[(10, '10 - Obra-Prima'), (9, '9 - Ótimo'), (8, '8 - Muito Bom'), (7, '7 - Bom'), (6, '6 - Aceitável'), (5, '5 - Mediano'), (4, '4 - Ruim'), (3, '3 - Muito Ruim'), (2, '2 - Horrível'), (1, '1 - Terrível')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'anime_id')},
            },
        ),
    ]
