# Generated by Django 5.2.5 on 2025-09-26 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=300)),
                ('title_english', models.CharField(blank=True, max_length=300, null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('episodes', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('anime_type', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('studios', models.CharField(blank=True, max_length=300)),
                ('genres', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AnimeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('watching', 'Assistindo'), ('completed', 'Completo'), ('ptw', 'Planejo Assistir')], default='ptw', max_length=20)),
                ('episodes_watched', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_entries', to='lists.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'anime')},
            },
        ),
    ]
