# Generated by Django 5.2.5 on 2025-11-22 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_to', to='lists.anime')),
                ('source_anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_from', to='lists.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'source_anime', 'recommended_anime'), name='unique_user_recommendation')],
            },
        ),
    ]
